"""Assemble the files that ship next to the dictionary itself.

Attribution is written in two places, because the two get separated: in the
``.ifo`` description field, which KOReader shows in the dictionary list, and as
LICENSE and ATTRIBUTION files inside the archive, which is what anyone
redistributing it has to keep.
"""

from __future__ import annotations

import json
import zipfile
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from .licensing import attribution_block, get_license, resolve_bundle_license

__all__ = ["PackageFiles", "ifo_description", "write_catalog", "write_package_files"]

_INSTALL_NOTE = """\
Installation (KOReader)
-----------------------

Copy the folder containing the .ifo / .idx / .dict.dz / .syn files into

    koreader/data/dict/

on your device, so that you end up with

    koreader/data/dict/{basename}/{basename}.ifo

Restart KOReader. The dictionary appears in the dictionary list; if several are
installed, long-press the dictionary name in a lookup popup to reorder them.

Not affiliated with the KOReader project.
"""


@dataclass(slots=True)
class PackageFiles:
    license_path: Path
    attribution_path: Path
    readme_path: Path
    bundle_license_id: str


def ifo_description(
    *,
    name: str,
    bundle_license_id: str,
    source_credits: Mapping[str, str],
    entries: int,
    forms: int,
) -> str:
    """Attribution compact enough to live in a single ``.ifo`` line.

    :func:`kdicts.writers.stardict.write_stardict` flattens newlines to
    ``<br>``, so this can be written as normal multi-line text.
    """
    lines = [
        f"{name} -- {entries} entries, {forms} inflected forms.",
        f"Licence: {bundle_license_id}.",
        "Sources: " + "; ".join(f"{k} ({v})" for k, v in sorted(source_credits.items())),
        "Generated by koreader-dicts. Not affiliated with the KOReader project.",
    ]
    return "\n".join(lines)


def write_package_files(
    directory: Path | str,
    *,
    name: str,
    basename: str,
    license_ids: Iterable[str],
    source_credits: Mapping[str, str],
    entries: int,
    forms: int,
    extra_notes: Sequence[str] = (),
) -> PackageFiles:
    """Write ``LICENSE``, ``ATTRIBUTION`` and ``README`` beside the dictionary."""
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    ids = sorted(set(license_ids))
    bundle = resolve_bundle_license(ids)

    # LICENSE: the outbound licence of the compilation, then every source
    # licence it was derived from.
    license_lines = [
        f"{bundle.name}",
        bundle.url,
        "",
        "This dictionary is a compilation of the sources listed in ATTRIBUTION.",
        "Each source's own terms are reproduced there and continue to apply to the",
        "material it contributed.",
        "",
    ]
    for license_id in ids:
        lic = get_license(license_id)
        license_lines.append(f"  * {lic.name} ({lic.id}) -- {lic.url}".rstrip(" -"))
    license_path = directory / "LICENSE"
    license_path.write_text("\n".join(license_lines).rstrip() + "\n", encoding="utf-8")

    # ATTRIBUTION: who to credit, per source, with the terms in full.
    attribution_path = directory / "ATTRIBUTION"
    attribution_path.write_text(attribution_block(ids, source_credits), encoding="utf-8")

    # README.txt: what this is and where to copy it on the device.
    readme_lines = [
        name,
        "=" * len(name),
        "",
        f"{entries} entries, {forms} inflected forms.",
        f"Built {datetime.now(UTC).strftime('%Y-%m-%d')} by koreader-dicts.",
        f"Licence: {bundle.id}. See LICENSE and ATTRIBUTION.",
        "",
        _INSTALL_NOTE.format(basename=basename),
    ]
    readme_lines.extend(extra_notes)
    readme_path = directory / "README.txt"
    readme_path.write_text("\n".join(readme_lines).rstrip() + "\n", encoding="utf-8")

    return PackageFiles(
        license_path=license_path,
        attribution_path=attribution_path,
        readme_path=readme_path,
        bundle_license_id=bundle.id,
    )


def write_zip(directory: Path | str, destination: Path | str | None = None) -> Path:
    """Zip a built dictionary folder for download.

    ZIP with DEFLATE. The payload is already part-compressed -- the
    ``.dict.dz`` is dictzip -- so most of the saving comes from the plain
    ``.idx`` and ``.syn`` indexes. Measured on the 21.6 MB en-pt build:

    ==========  =======  ==================================================
    method      size     note
    ==========  =======  ==================================================
    stored      21.6 MB  no compression
    deflate -9  15.1 MB  opens everywhere, 1.9 s
    bzip2       15.1 MB  no better, and not universally supported
    lzma        14.3 MB  5% smaller, 10 s, and stock Windows Explorer and
                         macOS Archive Utility cannot open it
    ==========  =======  ==================================================

    DEFLATE is the only format published, because stock Windows and macOS
    unzip it without extra software. The archive contains the dictionary folder
    itself, so unzipping into ``koreader/data/dict/`` lands the files at the
    right depth.
    """
    directory = Path(directory)
    destination = Path(destination) if destination else directory.with_suffix(".zip")
    destination.parent.mkdir(parents=True, exist_ok=True)
    files = sorted(p for p in directory.rglob("*") if p.is_file())
    with zipfile.ZipFile(destination, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in files:
            archive.write(path, path.relative_to(directory.parent))
    return destination


def write_catalog(path: Path | str, dictionaries: Sequence[Mapping[str, object]]) -> Path:
    """Write the catalog JSON the website renders.

    A flat document with no nesting beyond the per-dictionary records. The site
    is static and reads this at build time; it never runs the toolchain.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    document = {
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "schema": 1,
        "dictionaries": sorted(dictionaries, key=lambda d: str(d.get("pair", ""))),
    }
    path.write_text(
        json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return path
